---
apiVersion: v1
kind: Service
metadata:
  name: nsharma-redis-service
spec:
  type: ClusterIP
  selector:
    app: nsharma-test-redis
  ports:
  - name: nsharma-test-redis
    port: 6379
    targetPort: 6379
