---
apiVersion: v1
kind: Service
metadata:
  name: nsharma-flask-service
spec:
  type: ClusterIP
  selector:
    app: nsharma-test-flask
  ports:
  - name: nsharma-test-flask
    port: 5000
    targetPort: 5000
